# Generated by Django 3.2.6 on 2021-09-04 08:20
"""Make config of migrations models."""

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Create a new migrations of question and choice models."""

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                ('question_text', models.CharField(max_length=200)),
                (
                    'pub_date',
                    models.DateTimeField(verbose_name='date published')
                ),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                (
                    'question',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='polls.question'
                    )
                ),
            ],
        ),
    ]
