# Generated by Django 3.2.6 on 2021-09-11 08:58
"""Make config of migrations models."""

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    """Make migrations of datetime of questions model."""

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name='date ended'
            ),
            preserve_default=False,
        ),
    ]
