# Generated by Django 3.2.6 on 2021-09-11 09:33
"""Make config of migrations models."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Make migrations of datetime of questions model."""

    dependencies = [
        ('polls', '0002_question_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='date ended'
            ),
        ),
    ]
