# Generated by Django 3.2.6 on 2021-10-09 09:40
"""Make config of migrations models."""

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    """Make migration to set default date of end_date."""

    dependencies = [
        ('polls', '0003_alter_question_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name='date ended'
            ),
        ),
    ]
