# Generated by Django 3.2.6 on 2021-10-09 09:29
"""Make config of migrations models."""

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    """Make migrations of end_date of questions model."""

    dependencies = [
        ('polls', '0003_alter_question_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(
                default=datetime.datetime(
                    2021, 10, 9, 9, 29, 5, 995350,
                    tzinfo=utc
                ),
                verbose_name='date ended'
            ),
        ),
    ]
